name: Actions Runner Test 2

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test runner
        run: echo "GitHub Actions runner is available"
